name: QR CI
on:
    push:
        branches: [main, Development]
    pull_request:
        branches: [main, Development]
jobs: 
    build:
        name: Build for WebGL
        runs-on: ubuntu-latest

        steps:
        # Checkout
        - uses: actions/checkout@v4
        # Cache
        - uses: actions/cache@v3
          with:
              path: Library
              key: Library-QRGenerator-WebGL
              restore-keys: |
                  Library-QRGenerator-
                  Library-  
        # Tests
        - uses: game-ci/unity-test-runner@v4
          id: TestRunner
          env:
             UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
             UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
             UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          with:
             projectPath: Assets
             githubToken: ${{ secrets.GITHUB_TOKEN }}
             unityVersion: 6000.0.22f1
        # Test Results
        - uses: actions/upload-artifact@v4
          if: always()
          with:
            name: Test results
            path: ${{ steps.TestRunner.outputs.artifactsPath }} 
        # Code Coverage
        - uses: actions/upload-artifact@v4
          if: always()
          with:
            name: Coverage results
            path: ${{ steps.TestRunner.outputs.coveragePath }}
            
