name: QR CI
on:
    push:
        branches: [main, Development]
    pull_request:
        branches: [main, Development]
jobs: 
    tests:
        name: Unity Tests
        runs-on: ubuntu-latest

        steps:
        
        # Checkout
        - uses: actions/checkout@v4
        
        # Cache
        - uses: actions/cache@v3
          with:
            path: Library
            key: Library-${{ vars.PROJECT_NAME }}-WebGL
            restore-keys: |
                Library-${{ vars.PROJECT_NAME }}-
                Library-  
                
        # Tests
        - uses: game-ci/unity-test-runner@v4
          id: TestRunner
          env:
            UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
            UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
            UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          with:
            projectPath: .
            githubToken: ${{ secrets.GITHUB_TOKEN }}
            unityVersion: 6000.0.22f1
            
        # Test Results
        - uses: actions/upload-artifact@v4
          if: always()
          with:
            name: Test results
            path: ${{ steps.TestRunner.outputs.artifactsPath }} 
            
        # Code Coverage
        - uses: actions/upload-artifact@v4
          if: always()
          with:
            name: Coverage results
            path: ${{ steps.TestRunner.outputs.coveragePath }}
            
        # Show Diff
        - name: Show git diff
          run: git diff
          
    build:
        name: Build for WebGL
        runs-on: ubuntu-latest
        needs: tests
        if: success()

        steps:
        
        # Checkout
        - uses: actions/checkout@v4

        # Cache
        - uses: actions/cache@v3
          with:
            path: Library
            key: Library-${{ vars.PROJECT_NAME }}-WebGL
            restore-keys: |
              Library-${{ vars.PROJECT_NAME }}-
              Library-

        # Show Diff
        - name: Show git diff
          run: git diff
          
        # Builder (WebGL)
        - uses: game-ci/unity-builder@v4
          env:
            UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
            UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
            UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          with:
            targetPlatform: WebGL
            
        # Storing Build
        - uses: actions/upload-artifact@v4
          with:
            name: Build
            path: build
            
    deploy:
        name: Deploy to Github Pages
        runs-on: ubuntu-latest
        needs: build
        if: success()

        steps:
            # Checkout
            - uses: actions/checkout@v4

            # Checkout gh pages branch
            - name: Checkout gh-pages branch
              uses: peaceiris/actions-gh-pages@v3
              with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                target_branch: gh-pages
                source_dir: build/WebGL

            # Push the build to gh-pages
            - name: Deploy WebGL Build to Github Pages
              run: |
                git config --global user.name "Github Actions"
                git config --global user.email "actions@github.com"
                git add .
                git commit -m "Deploy WebGL Build"
                git push origin gh-pages
