name: QR CI
on:
    push:
        branches: [main, Development]
    pull_request:
        branches: [main, Development]
jobs: 
    build:
        name: Build for WebGL
        runs-on: ubuntu-latest

        steps:
        # Tests
        - uses: game-ci/unity-test-runner@v4
          id: TestRunner
          env:
             UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
             UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
             UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          with:
             packageMode: true
             projectPath: Assets
             githubToken: ${{ secrets.GITHUB_TOKEN }}
             unityVersion: 6000.0.22
        - uses: actions/upload-artifact@v3
          if: always()
          with:
            name: Test results
            path: ${{ steps.TestRunner.outputs.artifactsPath }} 
        - uses: actions/upload-artifact@v3
          if: always()
          with:
            name: Coverage results
            path: ${{ steps.TestRunner.outputs.coveragePath }}
            
